version: "3.3"
services:

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=plugat
      - POSTGRES_PASSWORD=plugat
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/01-init.sh
    networks:
      - backend

  plugat-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=plugat
      - DB_PASSWORD=plugat
    volumes:
      - ./config/keycloak:/opt/keycloak/config
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:

volumes:
  db-data:
